
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  branch = "master"
  name = "github.com/gin-contrib/multitemplate"

[[constraint]]
  branch = "master"
  name = "github.com/gin-contrib/sessions"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/jcelliott/lumber"

[[constraint]]
  branch = "master"
  name = "github.com/microcosm-cc/bluemonday"

[[constraint]]
  name = "github.com/russross/blackfriday"
  version = "1.5"

[[constraint]]
  branch = "master"
  name = "github.com/schollz/cryptopasta"

[[constraint]]
  branch = "master"
  name = "github.com/schollz/versionedtext"

[[constraint]]
  branch = "master"
  name = "github.com/shurcooL/github_flavored_markdown"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  name = "gopkg.in/urfave/cli.v1"
  version = "1.20.0"
